### ISSUE TITLE
Question: Why you are using "delete"

### ISSUE THREAD

**Issue by kholiavko-roman** [jakallergis/react-native-navigation-redux#1]
Hello! Thank you for you example!
Can you explain please, why you are usin "delete" operator inside NavigationWrapper `(Stack.js)`
```
delete newProps.dispatch
delete newProps.navigationState
```

I try delete it, all works fine. I don`t understand this lines of code.

**Comment by jakallergis** [comment]
Hi @kholiavko-roman 
Sorry for the late response.

These two lines are completely redundant right now. I should delete them.

I have a very large app with a lot of screens, from which i tried to extract code to create a very very simple example of the inner workings of this set (RN with navigation and redux).
In that app, i have some decorators to provide functionality for my components.
These two lines are there to avoid duplicates in the decorated components' props, as the decorator would take the screenProps from a component and add them to it's props as if they were passed directly to the component.
So im deleting the dispatch property because it will already be in the props and the navigationState because it is not needed anymore.

This example is a bit outdated though, as i have made more efficient, readable and complex examples than this. Whenever i find time i will make this example better, using a database as well.
